### ISSUE TITLE
Locking issues after update from 1.5.0 to >=1.6.0 (bug?)

### ISSUE THREAD

**Issue by serwer20** [appy-one/acebase#34]
Hi,

After updating acebase from 1.5.0 to 1.6.0 and higher I'm experiencing issues with "locking".

I didn't change my code and have no idea how to deal with those locking issues right now.

On 1.5.0 everything working really fast almost instantly, but on 1.6.0+ same functions take even 1 minute for lightweight tasks with `read lock on path ...` in the console.

```js
[localtest] Reading node "/user/1365174619/account" from address 2,60
[localtest] Reading node "/user/1365174619/account" from address 2,60
[localtest] Reading node "/user/1365174619/products/active" from address 1,789
[localtest] Reading node "/user/1365174619/account" from address 2,60
read lock on path "/" by tid 1 (Node.getInfo "/") is taking a long time to complete [1]
read lock on path "/" by tid 1 (Node.getInfo "/") is taking a long time to complete [2]
read lock on path "/" by tid 1 (Node.getInfo "/") is taking a long time to complete [3]
lock :: read lock on path "/" by tid 1 (Node.getInfo "/") took too long
[localtest] Node "/user/1365174619" being updated: adding 0 keys (), updating 0 keys (), removing 1 keys ("account")
[localtest] Node "/user/1365174619" saved at address 31,646 - 1 addresses, 24 bytes written in 1 chunk(s)
```

Are there any examples of "do this / don't do that" to avoid locking issues?

Node: 15.14.0

**Comment by appy-one** [comment]
I ran into the same issue this week, I will be publishing an update today that should fix it

**Comment by appy-one** [comment]
I have just published version 1.6.3, can you confirm this fixes your locking issue?

**Comment by serwer20** [comment]
> I have just published version 1.6.3, can you confirm this fixes your locking issue?

![image](https://user-images.githubusercontent.com/43101981/120800918-ce9e6d00-c540-11eb-8b75-129cc24fc277.png)

Now everything works fast but still getting locking issues in the console. 🤔

**Comment by appy-one** [comment]
Can you enable verbose logging in AceBase's settings and post the details? eg use: `new AceBase('dbname', { logLevel: 'verbose' })`

**Comment by appy-one** [comment]
Please let me know how to reproduce this. Can you submit code?

**Comment by serwer20** [comment]
This is strange, this lock issue appears in a random way now. I'm trying to find out minimal code to reproduce.

**Comment by appy-one** [comment]
Another something that might help me investigating.. Is your code running in a cluster (eg using `cluster.fork()`)?

**Comment by appy-one** [comment]
Also, do you have indexes on the data? Please give me some more info, this needs to be fixed asap!

**Comment by serwer20** [comment]
> Also, do you have indexes on the data? Please give me some more info, this needs to be fixed asap!

Sorry, I've been really busy lately.

 I've just sent you an email :)

**Comment by appy-one** [comment]
Thanks for the code, I managed to reproduce!
`ref.count()` appears to be the troublemaker here, I'll see what's going on there..

**Comment by appy-one** [comment]
I just published v1.6.4 which should fix this. Let me know if it works!

**Comment by serwer20** [comment]
now it works like a charm! gj 😁👍
